title: Prateek Dwivedi
description: PhD Student in Theoretical Computer Science
url: "https://prateekdwv.github.io/"
baseurl: ""

timezone: America/Vancouver
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
