title: Prateek Dwivedi
description: PhD Student in Theoretical Computer Science
url: "https://www.prateekdwivedi.in"
baseurl: ""

bluesky_did: "did:plc:y7erwx4j5fxmxafbg3wkhxf3"

timezone: America/Vancouver
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
